import * as dotenv from "dotenv";
import * as AWS from "aws-sdk";
AWS.config.update({ region: "ap-south-1" });
dotenv.config({
  path: `./config/${process.env.NODE_ENV}.env`,
});

const configs = {
  STAGE: process.env.STAGE,
  database: process.env.DATABASE,
  user: process.env.DB_USER,
  password: process.env.PASSWORD,
  host: process.env.HOST,
  port: process.env.DB_PORT,
  USERS_TABLE: "saev_user",
  SETTINGS_TABLE: "saev_setting",
  PERMISSIONS_TABLE: "saev_permission_master",
  ROLES_TABLE: "saev_role",
  ROLES_AND_PERMISSIONS_TABLE: "rolesandpermissions",
  TARIFF_PLANS_TABLE: "saev_tariff_plan",
  TARIFF_RULES_TABLE: "saev_tariff_rule",
  VEHICLES_TABLE: "saev_vehicle",
  TRIPS_TABLE: "saev_trip",
  FAVORITE_STATIONS_TABLE: "saev_favourite_station",
  USERS_OTP_TABLE: "saev_user_otp",
  STATIONS_TABLE: "saev_charge_station",
  STATIONS_MEDIA_TABLE: "saev_station_media",
  CHARGING_POINTS_TABLE: "saev_charge_point",
  OCCP_CHARGING_POINTS_TABLE: "saev_ocpp_charge_point",
  OCPP_VID_TAG_TABLE: "saev_ocpp_vid_tag",
  CHARGING_CONNECTORS_TABLE: "saev_charge_connector",
  CHARGING_SESSIONS_TABLE: "saev_charging_session",
  CHARGING_SESSION_LOGS_TABLE: "saev_charging_session_log",
  CHARGE_POINT_TABLE: "saev_charge_point",
  RFID_TABLE: "saev_rfid",
  ID_TAG_TABLE: "saev_ocpp_id_tag",
  USER_ROLES: "saev_user_role",
  LEVEL_HEADER_TABLE: "saev_level_header",
  LEVEL_ITEM_TABLE: "saev_level_item",
  BUSINESS_UNIT_TABLE: "saev_business_unit",
  OCPP_TRANSACTION_TABLE: "saev_ocpp_transaction",
  OCPP_METER_TABLE: "saev_ocpp_meter_value",
  OCCP_MESSAGE_LOG_TABLE: "saev_ocpp_message_log",
  ALERT_TABLE: "saev_alert",
  ANALYTICS_TABLE: "saev_analytics",
  CHARGE_POINT_UNAVAILABILITY: "saev_charge_point_unavailability",
  SUPER_ADMIN: "saev_super_admin",
  VID_TABLE: "saev_vid",
  TEAM_HEADER: "saev_team_hdr",
  TEAM_DETAILS: "saev_team_dtl",
  TEAM_INVOICE: "saev_team_invoice",
  PAYMENT_TABLE: "saev_payment",
  USER_DEVICES: "saev_user_devices",
  NOTIFICATIONS: "saev_notifications",
  SEQUENCE_GENERATOR: "saev_sequence_number",
  corsBaseUrl: "*",
  cookieSecretKey: "-",
  apiListenPort: process.env.PORT || 4000,
  occpWebSocketIp: process.env.OCPP_IP,
  WALLET_TRANSACTION_TABLE: "saev_wallet_transaction",
  DISCOUNTS_TABLE: "saev_discount",
  NOTIFY_HEADER_TABLE:"saev_notification_hdr",
  sendSMS: process.env.sendSMS || false,
  masterOtp: process.env.masterOtp || 1234,
  JSREPORT_SERVER_URL: process.env.JSREPORT_SERVER_URL,
  FROM_EMAIL_ID: process.env.FROM_EMAIL_ID,
  MD_VEHICLE_TABLE: "saev_md_vehicle",
  MD_CHARGER_TABLE: "saev_md_charger",
  MD_CONNECTOR_TABLE :"saev_md_connector",
  SYSTEM:"System",
  FIRMWARE_MANAGEMENT:"saev_firmware_management",
  ocppTempEndpoint: "http://3.109.231.113:9893"
};

export default configs;
