/* Permission master data*/
INSERT INTO public.saev_permission_master (name,displayname,createdat,updatedat,"module",actiontype) VALUES
    ('USER_MANAGEMENT:VIEW','user management','now()','now()','USER_MANAGEMENT','VIEW'),
    ('TARIFF:VIEW','tariff','now()','now()','TARIFF','VIEW'),
    ('CHARGING_SESSIONS:VIEW','charging sessions','now()','now()','CHARGING_SESSIONS','VIEW'),
    ('CUSTOMER_PROFILE:MODIFY','customer profile','now()','now()','CUSTOMER_PROFILE','MODIFY'),
    ('USER_MANAGEMENT:MODIFY','user management','now()','now()','USER_MANAGEMENT','MODIFY'),
    ('USER_MANAGEMENT:DELETE','user management','now()','now()','USER_MANAGEMENT','DELETE'),
    ('TARIFF:MODIFY','tariff','now()','now()','TARIFF','MODIFY'),
    ('TARIFF:CREATE','tariff','now()','now()','TARIFF','CREATE'),
    ('USER_MANAGEMENT:CREATE','user management','now()','now()','USER_MANAGEMENT','CREATE'),
    ('ALERTS:VIEW','alerts','now()','now()','ALERTS','VIEW'),
    ('ALERTS:MODIFY','alerts','now()','now()','ALERTS','MODIFY'),
    ('BUSINESS_UNIT:VIEW','business unit','now()','now()','BUSINESS_UNIT','VIEW'),
    ('BUSINESS_UNIT:CREATE','business unit','now()','now()','BUSINESS_UNIT','CREATE'),
    ('BUSINESS_UNIT:MODIFY','business unit','now()','now()','BUSINESS_UNIT','MODIFY'),
    ('BUSINESS_UNIT:DELETE','business unit','now()','now()','BUSINESS_UNIT','DELETE'),
    ('AUTHENTICATION:VIEW','authentication','now()','now()','AUTHENTICATION','VIEW'),
    ('AUTHENTICATION:MODIFY','authentication','now()','now()','AUTHENTICATION','MODIFY'),
    ('AUTHENTICATION:DELETE','authentication','now()','now()','AUTHENTICATION','DELETE'),
    ('TENANT:MODIFY','tenant','now()','now()','TENANT','MODIFY'),
    ('AUTHENTICATION:CREATE','authentication','now()','now()','AUTHENTICATION','CREATE'),
    ('CHARGE_POINT:VIEW','charge point','now()',NULL,'CHARGE_POINT','VIEW'),
    ('REPORTS:VIEW','Reports','now()','now()','REPORTS','VIEW'),
    ('DISCOUNTS:VIEW','discounts','now()','now()','DISCOUNTS','VIEW'),
    ('DISCOUNTS:CREATE','discounts','now()','now()','DISCOUNTS','CREATE'),
    ('DISCOUNTS:MODIFY','discounts','now()','now()','DISCOUNTS','MODIFY'),
    ('DISCOUNTS:DELETE','discounts','now()','now()','DISCOUNTS','DELETE'),
    ('NOTIFICATIONS:VIEW','Notifications','now()','now()','NOTIFICATIONS','VIEW'),
    ('NOTIFICATIONS:CREATE','Notifications','now()','now()','NOTIFICATIONS','CREATE'),
    ('NOTIFICATIONS:MODIFY','Notifications','now()','now()','NOTIFICATIONS','MODIFY'),
    ('NOTIFICATIONS:DELETE','Notifications','now()','now()','NOTIFICATIONS','DELETE'),
    ('CHARGING_SESSIONS:MODIFY','charging sessions','now()','now()','CHARGING_SESSIONS','MODIFY'),
    ('CHARGE_STATION:MODIFY','charge station','now()','now()','CHARGE_STATION','MODIFY'),
    ('CHARGING_SESSIONS:ACTION_REMOTE_STOP','Remote Stop',NULL,NULL,'CHARGING_SESSIONS','ACTION'),
    ('TEAMS:CREATE','teams','now()','now()','TEAM_MANAGEMENT','CREATE'),
    ('TEAMS:MODIFY','teams','now()','now()','TEAM_MANAGEMENT','MODIFY'),
    ('AUTHENTICATION:ACTION_APPROVE_AUTOCHARGE_REQUEST','Approve autocharge request',NULL,NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_MARK_RFID_AS_SHIPPED','Mark RFID as shipped','now()',NULL,'AUTHENTICATION','ACTION'),
    ('CHARGE_STATION:VIEW','charge station','now()','now()','CHARGE_STATION','VIEW'),
    ('CUSTOMER_PROFILE:ACTION_TOPUP','Topup','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('CUSTOMER_PROFILE:ACTION_REFUND','Refund','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('CUSTOMER_PROFILE:ACTION_REMOTE_START','Remote start','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('CUSTOMER_PROFILE:ACTION_REMOTE_STOP','Remote stop','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('CUSTOMER_PROFILE:ACTION_DOWNLOAD_INVOICE','Download invoice','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('CUSTOMER_PROFILE:ACTION_SEND_VERFICATION_LINK','Send verification link','now()',NULL,'CUSTOMER_PROFILE','ACTION'),
    ('AUTHENTICATION:ACTION_ACTIVATE_RFID','Activate RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_DEACTIVATE_RFID','Deactivate RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_ASSIGN_RFID','Assign RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_UNASSIGN_RFID','Unassign RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_UNASSIGN_AUTOCHARGE','Unassign Autocharge','now()',NULL,'AUTHENTICATION','ACTION'),
    ('AUTHENTICATION:ACTION_BULK_ASSIGN_RFID','Bulk assign RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('TARIFF:ACTION_SETUP_MINIMUM_BALANCE','Set up minimum balance','now()',NULL,'TARIFF','ACTION'),
    ('TARIFF:ACTION_ASSIGN_TARIFF','Assign Tariff','now()',NULL,'TARIFF','ACTION'),
    ('REPORTS:ACTION_CHARGING_TRANSACTION','Charging Transaction Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_TEAM_TRANSACTION','Team Transaction Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_WALLET_TRANSACTION','Wallet Transaction Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_BILLING','Billing Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_INDIVIDUAL_USER','Individual User Registration Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_CHARGE_POINT','ChargePoint Report',NULL,NULL,'REPORTS','ACTION'),
    ('CHARGE_STATION:CREATE','charge station','now()','now()','CHARGE_STATION','CREATE'),
    ('CHARGE_STATION:DELETE','charge station','now()','now()','CHARGE_STATION','DELETE'),
    ('TEAMS:VIEW','teams','now()','now()','TEAM_MANAGEMENT','VIEW'),
    ('TEAMS:DELETE','teams','now()','now()','TEAM_MANAGEMENT','DELETE'),
    ('CUSTOMER_PROFILE:VIEW','customer profile','now()','now()','CUSTOMER_PROFILE','VIEW'),
    ('FINANCE_AND_REVENUE:VIEW','Finance and revenue','now()','now()','FINANCE_AND_REVENUE','VIEW'),
    ('REPORTS:ACTION_GROUP_USER_REG','Group User Registration Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_CUST_WALLET_BAL','Customer Wallet Balance Report','now()',NULL,'REPORTS','ACTION'),
    ('REPORTS:ACTION_NEW_CUSTOMER_REG','New Customer Registration Report','now()',NULL,'REPORTS','ACTION'),
    ('CHARGE_STATION:ACTION_REMOTE_START','Remote start','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:ACTION_REMOTE_STOP','Remote stop','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:ACTION_HARD_RESET','Hard reset','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:ACTION_SOFT_RESET','Soft reset','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:ACTION_CHARGER_CONFIG','Charger configuration','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:ACTION_CLEAR_CACHE','Clear Cache','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:SET_CHARGER_AVAIL','Set charger availability','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:SET_CONNECTOR_AVAIL','Set connector availability','now()',NULL,'CHARGE_STATION','ACTION'),
    ('CHARGE_STATION:VIEW_OCPP_LOGS','OCPP logs','now()',NULL,'CHARGE_STATION','ACTION'),
    ('AUTHENTICATION:ACTION_BULK_IMPORT_RFID','Bulk import RFID','now()',NULL,'AUTHENTICATION','ACTION'),
    ('REPORTS:ACTION_TALLY_REPORT','Tally Report','now()','now()','REPORTS','ACTION'),
    ('CHARGE_STATION:ACTION_EXPORT_OCPP','Export OCPP logs','now()','now()','CHARGE_STATION','ACTION');


/* Sequence related data */
    INSERT INTO saev_sequence_number (tenantid, prefix, finyear,suffix,is_active,reference,created_at,updated_at,created_by,updated_by) VALUES
    (null, 'INV', 23,'00000000',true,'SESSION_INVOICE','now()','now()','SYSTEM','SYSTEM'),
    (null, 'INV', 23,'00000000',true,'TOP_UP','now()','now()','SYSTEM','SYSTEM'),
    (null, 'INV', 23,'00000000',true,'REFUND','now()','now()','SYSTEM','SYSTEM');



    INSERT INTO saev_level_header (tenant_id, level, name,created_at,) VALUES
    (null, '1', 'Country','now()'),
    (null, '2', 'Region'),
    (null, '3', 'State');

